nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
      - "redis"
      - "gearman"
    volumes:
      - ~/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

redis:
    build: ./redis
    ports:
      - "6379:6379"

gearman:
    build: ./gearman
    ports:
      - "4730:4730"
    volumes:
      - ~/opt:/opt
